Web_books2/urls.py
from django.contrib import admin
from django.urls import include, path
from catalog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
 path('', include('catalog.urls')),
 path('admin/', admin.site.urls),
]

if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path, include
from .import views
# добавлено для работы с медиа файлами
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books-list'),
    path('books/<int:pk>/', views.BookDetailView.as_view(),
         name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors-list'),
    path('authors/<int:pk>/', views.AuthorDetailView.as_view(),
         name='authors-detail'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(),
         name='my-borrowed'),
    path('edit_authors/', views.edit_authors, name='edit_authors'),
    path('edit_authors/<int:id>', views.edit_authors, name='edit_authors1'),
    path('authors_add/', views.add_author, name='authors_add'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('edit_author/<int:id>/', views.edit_author, name='edit_author')

]

# добавлено для работы с медиа файлами локально
if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# добавлено для регистрации входа пользователей
urlpatterns += [
 path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
from datetime import date

@property
def is_overdue(self):
 if self.due_back and date.today() > self.due_back:
    return True
 return False

# жанры книг
class Genre(models.Model):
    name = models.CharField(max_length=200,
    help_text=" Введите жанр книги",
    verbose_name="Жанр книги")

    def __str__(self):
        return self.name


# язык книги
class Language(models.Model):
    name = models.CharField(max_length=20,
    help_text=" Введите язык книги",
    verbose_name="Язык книги")
    def __str__(self):
        return self.name


# издательство
class Publisher(models.Model):
    name = models.CharField(max_length=20,
    help_text=" Введите наименование издательства",
    verbose_name="Издательство")
    def __str__(self):
        return self.name


# авторы
class Author(models.Model):
    first_name = models.CharField(max_length=100,
    help_text="Введите имя автора",
    verbose_name="Имя автора")
    last_name = models.CharField(max_length=100,
    help_text="Введите фамилию автора",
    verbose_name="Фамилия автора")
    date_of_birth = models.DateField(
    help_text="Введите дату рождения",
    verbose_name="Дата рождения",
    null=True, blank=True)
    about = models.TextField(help_text="Введите сведения об авторе",
    verbose_name="Сведения об авторе")
    photo = models.ImageField(upload_to='images',
    help_text="Введите фото автора",
    verbose_name="Фото автора",
    null=True, blank=True)

    def __str__(self):
        return self.last_name

class Gun(models.Model):
    title = models.CharField(max_length=200,
    help_text="Введите название книги",
    verbose_name="Название книги")
    summary = models.TextField(max_length=1000,
    help_text="Введите краткое описание книги",
    verbose_name="Аннотация книги")
    photo = models.ImageField(upload_to='images',
    help_text="Введите изображение обложки",
    verbose_name="Изображение обложки")

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        # Возвращает URL-адрес для доступа к
        # определенному экземпляру книги
        return reverse('book-detail', args=[str(self.id)])

# книги
class Book(models.Model):
    title = models.CharField(max_length=200,
    help_text="Введите название книги",
    verbose_name="Название книги")
    genre = models.ForeignKey('Genre',
    on_delete=models.CASCADE,
    help_text=" Выберите жанр для книги",
    verbose_name="Жанр книги", null=True)
    language = models.ForeignKey('Language',
    on_delete=models.CASCADE,
    help_text="Выберите язык книги",
    verbose_name="Язык книги", null=True)
    publisher = models.ForeignKey('Publisher',
    on_delete=models.CASCADE,
    help_text="Выберите издательство",
    verbose_name="Издательство", null=True)
    year = models.CharField(max_length=4,
    help_text="Введите год издания",
    verbose_name="Год издания")
    author = models.ManyToManyField('Author',
    help_text="Выберите автора (авторов)книги",
    verbose_name="Автор (авторы) книги")
    summary = models.TextField(max_length=1000,
    help_text="Введите краткое описание книги",
    verbose_name="Аннотация книги")
    isbn = models.CharField(max_length=13,
    help_text="Должно содержать 13 символов",
    verbose_name="ISBN книги")
    price = models.DecimalField(decimal_places=2, max_digits=7,
    help_text="Введите цену книги",
    verbose_name="Цена (руб.)")
    photo = models.ImageField(upload_to='images',
    help_text="Введите изображение обложки",
    verbose_name="Изображение обложки")

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        # Возвращает URL-адрес для доступа к
        # определенному экземпляру книги
        return reverse('book-detail', args=[str(self.id)])


class Status(models.Model):
    name = models.CharField(max_length=20,
    help_text="Введите статус экземпляра книги",
    verbose_name="Статус экземпляра книги")
    def __str__(self):
        return self.name


# экземпляр книги
class BookInstance(models.Model):
 book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
 inv_nom = models.CharField(max_length=20, null=True, help_text="Введите инвентарный номер экземпляра", verbose_name="Инвентарный номер")
 status = models.ForeignKey('Status', on_delete=models.CASCADE, null=True, help_text='Изменить состояние экземпляра', verbose_name="Статус экземпляра книги")
 due_back = models.DateField(null=True, blank=True, help_text="Введите конец срока статуса", verbose_name="Дата окончания статуса")
 borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Заказчик", help_text='Выберите заказчика книги')
 objects = models.Manager

 # Метаданные
 class Meta:
    ordering = ["due_back"]
 def __str__(self):
    return '%s %s %s' % (self.inv_nom, self.book, self.status)
 @property
 def is_overdue(self):
     if self.due_back and date.today() > self.due_back:
         return True
     return False

catalog/forms.py
from django import forms
from datetime import date

from catalog.models import Gun


# форма для добавления в БД новых авторов
class Form_add_author(forms.Form):
 title = forms.CharField(label="Название экспоната")
 summary = forms.CharField(label="Описане", widget=forms.Textarea)
 photo = forms.ImageField(label="Фото автора")


class Form_edit_author(forms.ModelForm):
 class Meta:
  model = Gun
  fields = '__all__'

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.views.generic import ListView, DetailView
from catalog.models import Book, BookInstance, Author, Gun
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

def index(request):
 text_head = 'На нашем сайте вы можете ознакомиться с нашими экспонатами.'
 # Данные о книгах и их количестве
 guns = Gun.objects.all()
 num_books = Book.objects.all().count()
 # Данные об экземплярах книг в БД
 num_instances = BookInstance.objects.all().count()
 # Доступные книги (статус = 'На складе')
 num_instances_available = BookInstance.objects.filter(
 status__exact=2).count()
 # Данные об авторах книг
 authors = Author.objects
 num_authors = Author.objects.count()
 # Количество посещений этого view, подсчитанное в переменной session
 num_visits = request.session.get('num_visits', 0)
 request.session['num_visits'] = num_visits + 1
 # Словарь для передачи данных в шаблон index.html
 context = {'text_head': text_head,
 'guns': guns, 'num_books': num_books,
 'num_instances': num_instances,
 'num_instances_available': num_instances_available,
 'authors': authors, 'num_authors': num_authors,
 'num_visits': num_visits
 }
 # передача словаря context с данными в шаблон
 return render(request, 'catalog/index.html', context)


class BookListView(ListView):
    model = Gun
    context_object_name = 'gun'
    paginate_by = 10

class BookDetailView(DetailView):
    model = Gun
    context_object_name = 'gun'


class AuthorListView(ListView):
    model = Gun
    paginate_by = 4


class AuthorDetailView(DetailView):
    model = Author


def about(request):
    text_head = 'О нас'
    name = 'ООО "Музей оружия Курск"'
    rab1 = 'Сбор, сохранение, интерпретация и демонстрация предметов, имеющих художественное, культурное или научное значение для изучения и образования общественности. С точки зрения посетителя или сообщества, эта цель также может зависеть от точки зрения человека.'
    rab2 = 'Распознавание объектов дорожной инфраструктуры'
    rab3 = 'Создание графических АРТ-объектов на основе' \
    ' систем искусственного интеллекта'
    rab4 = 'Создание цифровых интерактивных книг, учебных пособий' \
    ' автоматизированных обучающих систем'
    context = {'text_head': text_head, 'name': name,
    'rab1': rab1, 'rab2': rab2,
    'rab3': rab3, 'rab4': rab4}
    # передача словаря context с данными в шаблон
    return render(request, 'catalog/about.html', context)

def contact(request):
    text_head = 'Контакты'
    name = 'ООО "Музей оружия Курск"'
    address = 'Курск, ул. Гагарина, д. 27 '
    tel = '+7 (920) 268 22-10'
    email = 'teatrekursk@mail.ru'
    # Словарь для передачи данных в шаблон index.html
    context = {'text_head': text_head,
    'name': name, 'address': address,
    'tel': tel,
    'email': email}
    # передача словаря context с данными в шаблон
    return render(request, 'catalog/contact.html', context)


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
 # Универсальный класс представления списка книг,
 # находящихся в заказе у текущего пользователя
 model = BookInstance
 template_name = 'catalog/bookinstance_list_borrowed_user.html'
 paginate_by = 10

 def get_queryset(self):
    return BookInstance.objects.filter(
        borrower=self.request.user).filter(
        status__exact='2').order_by('due_back')


# вызов страницы для редактирования авторов
def edit_authors(request):
 gun = Gun.objects.all()
 context = {'gun': gun}
 return render(request, "catalog/edit_authors.html", context)

def edit_author(request, id):
 gun = Gun.objects.get(id=id)
 # author = get_object_or_404(Author, pk=id)
 if request.method == "POST":
    instance = Gun.objects.get(pk=id)
    form = Form_edit_author(request.POST, request.FILES, instance=instance)
    if form.is_valid():
        form.save()

        return HttpResponseRedirect("/edit_authors/")
 else:
    form = Form_edit_author(instance=gun)
    content = {"form": form}
    return render(request, "catalog/edit_author.html", content)

# импорт для добавления автора
from .forms import Form_add_author, Form_edit_author
from django.urls import reverse
# Создание нового автора в БД
def add_author(request):
 if request.method == 'POST':
    form = Form_add_author(request.POST, request.FILES)
    if form.is_valid():
     #получить данные из формы
        title = form.cleaned_data.get("title")
        summary = form.cleaned_data.get("summary")
        photo = form.cleaned_data.get("photo")
        # создать объект для записи в БД
        obj = Gun.objects.create(
        title=title,
        summary=summary,
        photo=photo)
        # сохранить полученные данные
        obj.save()
    # загрузить страницу со списком автором
        return HttpResponseRedirect(reverse('edit_authors'))
 else:
    form = Form_add_author()
    context = {"form": form}
    return render(request, "catalog/authors_add.html", context)


# удаление авторов из БД
def delete(request, id):
 try:
    gun = Gun.objects.get(id=id)
    gun.delete()
    return HttpResponseRedirect("/edit_authors/")
 except:
    return HttpResponseNotFound("<h2>Эксонат не найден</h2>")

templates/catalog/about.html
{% extends "catalog/base.html" %}
<head>
{% load static %}
</head>
{% block content %}

<!-- Карусель -->

<h4 class="text-center">{{ text_head }}</h4>
<div class="row my-2 text-center">
<div class="col-5"></div>
<div class="col-1 text-center">
<img src="{% static 'images/p100.png' %}">
</div>
<div class="col-5"></div>
</div>
<div class="row my-2 text-primary text-center">
<h3 class="text-body">{{ name }}</h3>
</div>
<div class="row my-2 text-white text-start">
<div class="col mx-2 my-2 bg-secondary text-body">{{rab1}}</div>

</div>
</div>

{% endblock %}

templates/catalog/author_detail.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="container text-start">
<div class="row my-2">
<h4>{{ object.first_name }} {{author.last_name}}</h4>
<p>Родился - {{author.date_of_birth}}</p>
<p>Фото (портрет)</p>
<p><img src="{{ author.photo.url }}"
alt="connect" style="max-height:200px"></p>
<div class="row my-2">
<div class="col-2 my-2">
<a href="{{ author.photo.url}}" class="btn btn-primary"
target="_blank"> Показать</a>
</div>
</div>
<div class="row my-2">
{{author.about}}
</div>
</div> 
</div>
{% endblock %}

templates/catalog/author_list.html
{% extends "catalog/base.html" %}
{% block content %}
<h4>Список авторов книг</h4>
{% if gun %}
<table class="table table-striped table-bordered text-start">
<thead>
<tr>
<th>Автор</th>
<th>Фото</th>
<th>Показать фото</th>
</tr>
</thead>
<tbody>
{% for author in gun.all %}
<tr>
<td><a href="{{ author.id }}">{{ author.title}}
{{author.last_name}} </a></td>
<td><img src="{{ author.photo.url }}" alt="connect"
style="max-height:100px"></td>
<td><a href="{{ author.photo.url}}"
class="btn btn-primary"
target="_blank"> Показать</a></td>
</tr>
{% endfor %}
<tbody>
</table>
{% else %}
<p>В базе данных нет авторов</p>
{% endif %}
{% endblock %}

templates/catalog/authors_add.html
{% extends "catalog/base.html" %}
{% block content %}
<h5>Добавить новый экспонат</h5>
<form action="" method="POST" enctype="multipart/form-data">
 {% csrf_token %}
 <div class="row">
 <div class="col-2 "></div>
 <div class="col-8 ">
 <table class="table text-start">
 {{ form }}
 </table>
 </div>
 <div class="col-2"></div>
 </div>
 <input type="submit" value="Сохранить" >
</form>
{% endblock %}

templates/catalog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/static/css/bootstrap.min.css" >
<script defer src="/static/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<div class="container-fluid p-1 bg-dark text-white text-center">
<div class="row">
<div class="col-2 text-start">
<img src="{% static 'images/p100.png' %}" width="70" height="70">
</div>
<div class="col-10 ">
<h3>Музей - 'Музей оружия Курск'</h3>
</div>
</div>
</div>
<div class="container-fluid">
<div class="row bg-warning text-center">
<div class="container-fluid">
<div class="row bg-secondary text-center">
<h6>
<a class="text-light" href="{% url 'index' %}">Главная страница</a>
<a class="text-light" href="{% url 'about' %}">О компании</a>
<a class="text-light" href="{% url 'contact' %}">Контакты</a>
</h6>
</div>
</div>
</div>
</div>
<div class="container-fluid">
<div class="row text-center text-primary fs-1 fw-bold">
<div>{% block header%}
{% endblock header %}
</div>
</div>
<div class="row text-start text-body">
<div class="col-2 bg-light">
 {% block sidebar %}
 <nav class="nav flex-column">
 <a class="nav-link text-body" href="{% url 'books-list' %}">Наши экспонаты</a>
 {% if user.is_authenticated %}
 <a class="nav-link text-body" style="margin-top: 150px"
 href="{% url 'logout'%}?next={{request.path}}">Выход</a>
 <div>Вошел админ: {{ user.get_username }}</div>
 <a class="nav-link text-body"
 href="/authors_add/{{authors_add}}">Добавить экспонат</a>
 <a class="nav-link text-body"
 href="{% url 'edit_authors' %}">Редактировать экспонаты</a>

 {% else %}
 <a class="nav-link text-body" style="margin-top: 150px"
 href="{% url 'login'%}?next={{request.path}}">Вход(для админов)</a>
 {% endif %}
</nav>
{% endblock sidebar %}

</div>

<div class="col-10" >
<div class="row text-center">
{% block content%}
{% endblock content %}
<!-- пагинатор -->
<div class="pagination">
<span class="step-links">
{% if page_obj.paginator.num_pages > 1 %}
{% if page_obj.has_previous %}
<a href="?page=1">&laquo; Первая</a>
<a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
{% endif %}
<span class="current">

Стр. {{ page_obj.number }}
из {{ page_obj.paginator.num_pages }}.
</span>
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">Следующая</a>
<a href="?page={{ page_obj.paginator.num_pages }}">Предыдущая &raquo;</a>
{% endif %}
{% endif %}
</span>
</div>
<!-- пагинатор -->
</div>
</div>
</div>
</div>
<div class="container-fluid">
<div class="row bg-secondary text-center text-dark small lh-sm pt-2 my-2">
{% block footer %}
<p>Copyright ООО "Музей оружия Курск",
2023. Все права защищены</p>
{% endblock footer%}
</div>
</div>
</body>
</html>

</html>

templates/catalog/bookinstance_list_borrowed_user.html
{% extends "catalog/base.html" %}
{% block content %}
 <h1>Взятые книги</h1>
 {% if bookinstance_list %}
 {% for bookinst in bookinstance_list %}
 <div class="{% if bookinst.is_overdue %} text-danger{% endif %}">
 <a href="{% url 'book-detail' bookinst.book.pk %}">
 {{bookinst.book.title}}</a>
 {{ bookinst.due_back }}
 </div>
 {% endfor %}
 {% else %}
 <p>Нет книг со статусом В ЗАКАЗЕ.</p>
 {% endif %}
{% endblock %}

templates/catalog/contact.html
{% extends "catalog/base.html" %}
<head>
{% load static %}
</head>
{% block content %}
<div class="container-fluid">
<div class="row my-2 text-center">
<div class="col-5"></div>
<div class="col-1 text-center">
<img src="{% static 'images/p100.png' %}">
</div>
<div class="col-5"></div>
</div>
<div class="row my-2 text-body text-center">
<h3>{{ name }}</h3>
</div>
<div class="row my-2 text-muted ">
<h4 class="text-center text-secondary">{{ text_head }}</h4>
</div>
<div class="row my-2">
<!-- пустые колонки слева от таблицы-->
<div class="col-3"></div>
<div class="col-6">
<table class="table table-striped table-bordered text-start">
<thead>
<tr>
<th>Адрес</th>
<th>Телефон</th>
<th>e-mail</th>
</tr>
</thead>
<tbody>
<tr>
<td>{{ address }}</td>
<td>{{ tel }}</td>
<td>{{ email }}</td>
</tr>
<tbody>
</table>
</div>
<!-- пустые колонки справа от таблицы-->
<div class="col-3"></div>
<!-- карта-->
<div class="row my-2 text-center">
<div class="col-2"></div>
<div class="col-8">
<img src="{% static 'images/ai.jpg' %}" class="img-fluid" >
</div>
<div class="col-2"></div>
</div>
</div>
{% endblock %}

templates/catalog/edit_author.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="row text-start lh-2">
 <h3>Изменить сведения об экспонате</h3>
</div>
<form method="post" enctype="multipart/form-data">
 {% csrf_token %}
 <table class="text-start">
 {% for field in form %}
 <tr>
 <th>{{ field.label_tag }}
 {{ field.errors }}
 </th>
 <th>{{ field }}</th>
 </tr>
 {% endfor %}

 <th>
 <button type="submit">Сохранить</button>
 </th>
 </table>
</form>
{% endblock %}

templates/catalog/edit_authors.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="row text-start lh-2">
 <h5>Список экспонатов для редактирования</h5>
</div>
 <div class="row">
 <div class="col-2 "></div>
 <a href="/authors_add/{{authors_add}}"></a>
 <div class="col-8 ">
 <table class="table table-striped table-bordered text-start">
 <thead>
 <tr>
 <th>Id</th>
 <th>Название</th>
 <th>Описание</th>
     <th>Фото</th>
 <th></th>

 </tr>
 </thead>
 <tbody>
 {% if gun %}
 {% for guns in gun.all %}
 <tr>
 <td>{{guns.id}}</td>
 <td>{{guns.title}}</td>
 <td>{{guns.summary}}</td>
  <td>
     <img src="{{guns.photo.url}}" alt="connect"
style="max-height:100px"></td>
 <td><a href="/edit_author/{{guns.id}}">Изменить</a>
    <a href="/delete/{{guns.id}}">Удалить</a></td>
 </tr>
 {% endfor %}
 {% else %}
 <p> В базе данных нет авторов</p>
 {% endif %}
 <tbody>
 </table>
 </div>
 <div class="col-2"></div>
 </div>
{% endblock %}

templates/catalog/gl.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/catalog/gun_detail.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="container text-start">
<div class="row my-2">
<h1>{{ gun.title }}</h1>
</div>
<div class="row my-2">
<p><strong></strong>
<div class="row my-2">


</div>
<img src="{{ gun.photo.url }}" alt="connect"
style="max-height:1000px; max-width: 1000px">
<a href="{{ gun.photo.url}}"
class="btn btn-primary"
target="_blank"> Показать</a>
<h1><strong>Описание:</strong></h1>
<h4>{{ gun.summary }}</h4>

</div>
</div>
{% endblock %}

templates/catalog/gun_list.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="row text-center text-dark lh-2">
<h4></h4>
</div>
{% if gun %}
<table class="table table-striped table-bordered text-start">
<thead>
<tr>
<th>Название</th>

<th>Экспонат</th>
<th>Показать экспонат</th>
</tr>
</thead>
<tbody>
{% for obj in gun %}
<tr>
<td><a href="{{ obj.id }}">{{ obj.title }} </a></td>


<td><img src="{{ obj.photo.url }}" alt="connect"
style="max-height:100px"></td>
<td><a href="{{ obj.photo.url}}"
class="btn btn-primary"
target="_blank"> Показать</a></td>
</tr>
{% endfor %}
</tbody>
</table>
{% else %}
<p>В базе данных нет экземпляров</p>
{% endif %}
{% endblock %}

templates/catalog/index.html
{% extends "catalog/base.html" %}
{% block title %}Мир книг{% endblock title %}
{% block header %}


{% endblock header %}
{% block content%}
    <h3 class="text-dark">Этот сайт разработан для хранения наших выстовочных экспонатов онлайн.</h3>
    <h5 class="text-dark">Приятного просмотра </h5>
    <div> </div>
<div class="row text-center text-dark lh-2">
 <h3>Наши экспонаты</h3>
 </div>
 {% if num_books > 0 %}
 <div class="row my-2">
 {% for obj in guns %}
 <div class="card" style="width: 20rem; height: 23rem;">
 <img src="{{ obj.photo.url }}" class="card-img-top">
 <div class="card-body">
 <p class="card-text small">
 {{obj.title}}
 </p>
 </div>
 </div>
 {% endfor %}
 </div>
 {% endif %}

 </div>
{% endblock content %}